(defun color-theme-shadow-moses ()
  (interactive)
  (color-theme-install
   '(color-theme-shadow-moses
      ((background-color . "#091a19")
      (background-mode . light)
      (border-color . "#021817")
      (cursor-color . "#000000")
      (foreground-color . "#70fff9")
      (mouse-color . "black"))
     (fringe ((t (:background "#021817"))))
     (mode-line ((t (:foreground "#02120a" :background "#289f85"))))
     (region ((t (:background "#000000"))))
     (font-lock-builtin-face ((t (:foreground "#f2cda1"))))
     (font-lock-comment-face ((t (:foreground "#ababab"))))
     (font-lock-function-name-face ((t (:foreground "#6424ff"))))
     (font-lock-keyword-face ((t (:foreground "#00e610"))))
     (font-lock-string-face ((t (:foreground "#02acf7"))))
     (font-lock-type-face ((t (:foreground"#757575"))))
     (font-lock-variable-name-face ((t (:foreground "#ef8101"))))
     (minibuffer-prompt ((t (:foreground "#04f1a0" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'color-theme-shadow-moses)
